INSERT INTO ATHLETE ( ID , NAME, SURNAME , SPORT , WEIGHT_CLASS ) VALUES ( '1' , 'GIUSEPPE', 'CIARDULLO', 'JUDO', 'CLASS_70KG');
INSERT INTO ATHLETE ( ID , NAME, SURNAME , SPORT , WEIGHT_CLASS ) VALUES ( '2' , 'IVO', 'METCHKAROV', 'WRESTLING', 'CLASS_70KG');
INSERT INTO ATHLETE ( ID , NAME, SURNAME , SPORT , WEIGHT_CLASS ) VALUES ( '3' , 'MATTIA', 'MANDARINO', 'JUDO', 'CLASS_80KG');
INSERT INTO ATHLETE ( ID , NAME, SURNAME , SPORT , WEIGHT_CLASS ) VALUES ( '4' , 'ALBERTO', 'BRUNO', 'WRESTLING', 'CLASS_80KG');
INSERT INTO ATHLETE ( ID , NAME, SURNAME , SPORT , WEIGHT_CLASS ) VALUES ( '5' , 'FRANCESCO', 'LO GULLO', 'WRESTLING', 'CLASS_80KG');
INSERT INTO ATHLETE ( ID , NAME, SURNAME , SPORT , WEIGHT_CLASS ) VALUES ( '6' , 'ALESSANDRO', 'LUPINACCI', 'WRESTLING', 'CLASS_60KG');